package pojos;
// Generated 29-jun-2024 22:33:18 by Hibernate Tools 4.3.1



/**
 * Lineasrecibo generated by hbm2java
 */
public class Lineasrecibo  implements java.io.Serializable {


     private int id;
     private Recibos recibos;
     private String concepto;
     private String subconcepto;
     private double baseImponible;
     private double porcentajeIva;
     private double importeIva;
     private double m3incluidos;
     private Double bonificacion;
     private Double importeBonificacion;

    public Lineasrecibo() {
    }

	
    public Lineasrecibo(int id, String concepto, String subconcepto, double baseImponible, double porcentajeIva, double importeIva, double m3incluidos) {
        this.id = id;
        this.concepto = concepto;
        this.subconcepto = subconcepto;
        this.baseImponible = baseImponible;
        this.porcentajeIva = porcentajeIva;
        this.importeIva = importeIva;
        this.m3incluidos = m3incluidos;
    }
    public Lineasrecibo(int id, Recibos recibos, String concepto, String subconcepto, double baseImponible, double porcentajeIva, double importeIva, double m3incluidos, Double bonificacion, Double importeBonificacion) {
       this.id = id;
       this.recibos = recibos;
       this.concepto = concepto;
       this.subconcepto = subconcepto;
       this.baseImponible = baseImponible;
       this.porcentajeIva = porcentajeIva;
       this.importeIva = importeIva;
       this.m3incluidos = m3incluidos;
       this.bonificacion = bonificacion;
       this.importeBonificacion = importeBonificacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Recibos getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Recibos recibos) {
        this.recibos = recibos;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getSubconcepto() {
        return this.subconcepto;
    }
    
    public void setSubconcepto(String subconcepto) {
        this.subconcepto = subconcepto;
    }
    public double getBaseImponible() {
        return this.baseImponible;
    }
    
    public void setBaseImponible(double baseImponible) {
        this.baseImponible = baseImponible;
    }
    public double getPorcentajeIva() {
        return this.porcentajeIva;
    }
    
    public void setPorcentajeIva(double porcentajeIva) {
        this.porcentajeIva = porcentajeIva;
    }
    public double getImporteIva() {
        return this.importeIva;
    }
    
    public void setImporteIva(double importeIva) {
        this.importeIva = importeIva;
    }
    public double getM3incluidos() {
        return this.m3incluidos;
    }
    
    public void setM3incluidos(double m3incluidos) {
        this.m3incluidos = m3incluidos;
    }
    public Double getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(Double bonificacion) {
        this.bonificacion = bonificacion;
    }
    public Double getImporteBonificacion() {
        return this.importeBonificacion;
    }
    
    public void setImporteBonificacion(Double importeBonificacion) {
        this.importeBonificacion = importeBonificacion;
    }




}


